pom.xml, singer/pom.xml, thrift-logger/pom.xml
Update pom.xml with setting that allows us to publish to maven-central using  `mvn deploy ...` command.
=> update pom.xml with maven repository publishing related settings

pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/config/ConfigFileServerSet.java, singer/src/main/java/com/pinterest/singer/config/ServersetMonitor.java, singer/src/main/java/com/pinterest/singer/utils/BrokerSetChangeListener.java, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigs.java
Remove Singer's dependency on finagle as finagle dependencies are no longer available in twitter's maven repos.
=> Remove Singer's dependency on finagle

CONTRIBUTING.md
=> Updated contrib guide

singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
Fixing metrics names for Singer k8s environment.
=> Fixing metrics names for Singer k8s environment

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml, thrift-logger/src/main/java/com/pinterest/singer/client/BaseThriftLoggerFactory.java, thrift-logger/src/main/java/com/pinterest/singer/client/logback/AppenderUtils.java, thrift-logger/src/test/java/com/pinterest/singer/client/AuditableLogbackThriftLoggerFactoryTest.java, thrift-logger/src/test/java/com/pinterest/singer/client/BaseThriftFactoryTest.java
1. upgrade logback to 1.1.8
2. configure thread to sleep x seconds before closing thrift loggers.
=> Two changes to thrift-logger module

singer/src/main/java/com/pinterest/singer/writer/KafkaWritingTask.java
Adding NPE fix proposed by @kabochya
=> Adding NPE fix proposed by @kabochya

AUTHORS.md
=> Update maintainers of Singer

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.8

singer-commons/src/main/thrift/config.thrift, singer/src/main/java/com/pinterest/singer/SingerMain.java, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
Make statspusher frequency of Singer configurable, default 60s
=> Make statspusher frequency of Singer configurable, default 60s

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.9

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer/pom.xml, thrift-logger/pom.xml
Increasing default metrics frequency to 180s and changing to 0.8.0.11
=> Increasing default metrics frequency to 180s and changing to 0.8.0.11

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.12

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer version 0.8.0.13

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
Singer version upgrade: Singer 0.8.0.14
=> Singer 0.8.0.14

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java, thrift-logger/pom.xml
Enable Memory Optimized Processor to be used via custom activation 0.8.0.15.
This PR connects the new MemoryOptimizedProcessor to be accessible via
=> Enable Memory Optimized Processor to be used via custom activation 0.8.0.15

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/main/java/com/pinterest/singer/writer/memq/MemqWriter.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/CommonUtils.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/Compression.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/DataCorruptionException.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/Deserializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/MemqLogMessage.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/MemqLogMessageIterator.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/MemqMessageHeader.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/UnknownCompressionException.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/serde/ByteArrayDeserializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/serde/ByteArraySerializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/serde/StringDeserializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/commons/serde/ThriftDeserializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/MemqProducer.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/MemqWriteResult.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/MemqWriteTaskResult.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/Serializer.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/TaskRequest.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/http/DaemonThreadFactory.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/http/HttpWriteTaskRequest.java, singer/src/main/java/com/pinterest/singer/writer/memq/producer/http/MemqHTTPProducer.java, singer/src/test/java/com/pinterest/singer/writer/memq/commons/TestUtils.java, singer/src/test/java/com/pinterest/singer/writer/memq/producer/TestMemqProducer.java, thrift-logger/pom.xml
Memq Writer Initial Commit with Singer 0.8.0.17
=> Memq Writer Initial Commit

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, thrift-logger/pom.xml
Add surrounding delimiter to envs, 0.8.0.19
=> Add surrounding delimiter to envs, 0.8.0.19

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java, thrift-logger/pom.xml
Fix env var delimiter and add metrics for tracking committable writers. Version 0.8.0.20
=> Fix env var delimiter and add metrics for tracking committable writers

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java, singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java, thrift-logger/pom.xml
Improve tests and refactor code for committable writers, fix env regex issue and added tests.
Singer version 0.8.0.21
=> Improve tests and refactor code for committable writers, fix env regex

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java, singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java, thrift-logger/pom.xml, thrift-logger/src/main/java/com/pinterest/singer/client/AuditableLogbackThriftLogger.java
1. singer.audit.num_uncorrupted_messages
2. audit.thrift_logger.checksum_added_to_log_message_count
=> Add crc related metrics and bump version to 0.8.0.23

singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java, singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
Add a metric to measure singer startup latency.
=> Add a metric to measure singer startup latency

singer/src/main/java/com/pinterest/singer/writer/KafkaProducerMetricsMonitor.java, singer/src/test/java/com/pinterest/singer/writer/TestKafkaProducerMetricsMonitor.java
Remove non-inclusive term from singer code.
=> Remove non-inclusive term from singer code

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer/pom.xml, thrift-logger/pom.xml
Enable Singer memory efficiency by default, Singer 0.8.0.25
=> Enable Singer memory efficiency by default

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/common/LogStreamProcessor.java, singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java, singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java, thrift-logger/pom.xml
Efficiency improvement along with code refactoring
=> Improvement to message key/value size metric implementation

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, thrift-logger/pom.xml
Enable Memq Auditor configs in Singer.
Singer 0.8.0.33
=> Enable Memq Auditor configs in Singer

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java, thrift-logger/pom.xml
Fix bug for missing cluster name config. Singer 0.8.0.34
=> Fix bug for missing cluster name config. Singer 0.8.0.34

singer-commons/src/main/thrift/config.thrift, singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/main/java/com/pinterest/singer/writer/NoOpLogStreamWriter.java, singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java, singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java, singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java, thrift-logger-python/tests/thrift_logger/test_thrift_logger.py
dummy -> no-op, sample (depending on the context)
=> Remove non-inclusive terminology from the code base

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer version 0.8.0.35

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/heartbeat/HeartbeatKafkaWriter.java, thrift-logger/pom.xml
Switch heartbeats to single partition to reduce connection counts. Version 0.8.0.36
=> Switch heartbeats to single partition to reduce connection counts

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer-commons/src/main/thrift/singer.thrift, singer/pom.xml, singer/src/main/java/com/pinterest/singer/common/LogStreamWriter.java, singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java, singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java, singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java, singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java, singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java, thrift-logger/pom.xml
Add environment variable header injections.
=> Add environment variable header injections

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.42

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
Upgrade Singer Kafka version to 2.3.1
=> Upgrade Singer Kafka version to 2.3.1

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.45

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.46

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
Singer version bump to 0.8.0.47
=> Singer version bump to 0.8.0.47

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.48

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.49

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.51

singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
Only update the file watcher if the serverset file hasn't been seen before
=> Fix duplicate memq serverset monitoring

pom.xml, singer-commons/pom.xml, singer-commons/src/main/java/com/pinterest/singer/config/ConfigFileWatcher.java, singer/pom.xml, singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java, thrift-logger/pom.xml
Add a test to validate only one watcher is created per MemQ serverset file
=> Update memq watcher tests and bump version to 0.8.0.52

singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
Fix buffer overflow issue due to prependhostname. Using 300 byte overhead to cover hostnames & timestamps with delimiters.
=> Fix buffer overflow issue due to prependhostname

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Singer 0.8.0.53

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump Singer version to 0.8.0.56

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.57

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/config/Decider.java, singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java, singer/src/test/java/com/pinterest/singer/monitor/DefaultLogMonitorTest.java, thrift-logger/pom.xml
Improve corner case handling and exception handling flow of the decider checks
Also bump version to 0.8.0.58
=> Improve exception handling in LogMonitor when creating LogStreamProcessors

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Update logback to 1.1.11

pom.xml, singer-commons/pom.xml, singer-commons/src/main/thrift/config.thrift, singer/pom.xml, singer/src/main/java/com/pinterest/singer/kubernetes/KubeService.java, singer/src/main/java/com/pinterest/singer/monitor/FileSystemEvent.java, singer/src/main/java/com/pinterest/singer/monitor/FileSystemEventFetcher.java, singer/src/main/java/com/pinterest/singer/monitor/FileSystemMonitor.java, singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java, singer/src/main/java/com/pinterest/singer/monitor/SelectiveUniqueFSEventQueue.java, singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java, singer/src/test/java/com/pinterest/singer/monitor/FileSystemMonitorTest.java, singer/src/test/java/com/pinterest/singer/monitor/LogDirectoryScannerTest.java, singer/src/test/java/com/pinterest/singer/monitor/TestSelectiveUniqueFSEventQueue.java, singer/teletraan/conf/singer.properties, thrift-logger/pom.xml
Add a Selective queue that deduplicates selected kinds of events before adding them to FileSystemEvents queue. Original design by: @ambud
=> Deduplicate FS Event Queue

pom.xml, singer-commons/pom.xml, singer/pom.xml, singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java, thrift-logger/pom.xml
Add variable to track number of messages skipped and written to take sampling into account for Kafka throughput metric
=> Fix kafka throughput metric when sampling is enabled

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.88

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
Version change: `0.8.0.89 -> 0.8.0.90`
=> Bump version to 0.8.0.90

pom.xml, singer-commons/pom.xml, singer/pom.xml, thrift-logger/pom.xml
=> Bump version to 0.8.0.94
