pinterest/singer

singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java

`DAILY_RESTART_TIME_END` used to be same as `DAILY_RESTART_TIME_BEGIN`, which will cause the restart time randomization fail to work.
Also changed the config check to verify if endTime is strictly larger than startTime.

Fix config typo

---

singer/src/test/java/com/pinterest/singer/SingerTestBase.java
singer/src/test/java/com/pinterest/singer/config/DirectorySingerConfiguratorTest.java
singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java

(1) fix testProcessLogStreamWithDecider in DefaultLogStreamProcessorTest.java :
The decider instance needs to reset to pass the test
(2) fix testConfiguratorLoadConfigsAndReceiveLiveChanges in DirectorySingerConfiguratorTest.java :
set property "writer.kafka.producerConfig.bootstrap.servers" to "127.0.0.1:9092", then SingerConfig can be loaded without checking "writer.kafka.producerConfig.broker.serverset" during unit test. However "writer.kafka.producerConfig.broker.serverset" should be used in production and it can tell Singer to discover kafka cluster.
(3) fix testLoadNewConfig in DirectorySingerConfiguratorTest.java :
modify SingerTestBase.java to have correct property setup for topic1 and topic2. With these changes, fixing testLoadNewConfig is straightforward.

Fixing the unit tests errors in singer

---

singer/src/main/java/com/pinterest/singer/common/SingerLog.java
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/monitor/MissingDirChecker.java
singer/src/test/java/com/pinterest/singer/monitor/MissingDirCheckerTest.java

MissingDirChecker is a daemon thread that get initialized, started and stopped in LogStreamManager.  When LogStreamManager tries to create LogStreams for each SingerLog, if the corresponding log directory (eg: /mnt/thrift_logger/) has not been created yet, the SingerLog will be put to a HashMap named singerLogsWithoutDir. MissingDirChecker will run every sleep_in_milliseconds (eg: 20 seconds) to check if the log directory for this SingerLog has been created. Once log directory has been created, LogStreamManager.initializeLogStreams method will be called for this SingerLog and SingerLog  will be removed from singerLogsWithoutDir if the method call does not throw any exception.

Implement MissingDirChecker

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/HeadersInjector.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/headersinjectors/LoggingAuditHeadersInjector.java
singer/src/test/java/com/pinterest/singer/writer/TestKafkaWriter.java

This PR is about:
(1) add HeadersProvider interface and LoggingAuditHeadersProvider implementation;
(2) make headersProviderClass an option for SingerConfig (similar to environmentProviderClass);
(3) make enableHeadersProvider an option for SingerLogConfig to allow per topic configuration;
(4) modify KafkaWriter.java to attach LoggingAuditHeaders if configured properly.

 Enables Singer to extract LoggingAuditHeaders from LogMessage and attach to the Headers of ProducerRecord

---

singer/src/main/java/com/pinterest/singer/common/SingerLog.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java
singer/src/test/java/com/pinterest/singer/utils/TestSingerUtils.java

Add support injection of Pod Uid instead of hostname for text logger. Logic:
If prepend hostname is enabled for text logger config & singer is running in Kubernetes mode then attempt to use pod id as hostname if pod if is NOT null or NON_KUBERNETES_POD_ID else return hostname.
```Results :
Tests run: 65, Failures: 0, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Singer Logging Agent 0.7.3.29:
[INFO] 
[INFO] Singer Logging Agent ............................... SUCCESS [  0.138 s]
[INFO] thrift-logger ...................................... SUCCESS [  8.141 s]
[INFO] singer ............................................. SUCCESS [02:32 min]
[INFO] ------------------------------------------------------------------ …
```

Add support injection of Pod Uid instead of hostname for text logger

---

singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/writer/KafkaProducerManager.java

Add metric to track number of kafka producers, this will help us determine if we need to tune the producer buffers to lower the memory footprint. Each producer uses 32MB buffer.memory by default which can add up if Singer is writing to a lot of Kafka clusters. 
Note that this buffer is allocated to the heap.

Add metric to track number of kafka producers, this will help us

---

singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/test/java/com/pinterest/singer/writer/TestKafkaWriter.java

Enable Singer to attach LoggingAuditHeaders if logging audit starts at Singer.
It is used for log files not generated by ThriftLogger.

Enable Singer to attach LoggingAuditHeaders

---

singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/AuditHeadersGenerator.java
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/LoggingAuditEventGenerator.java
singer-commons/src/main/thrift/loggingaudit.thrift

add timestamp field to logging audit headers. This timestamp is used to bucket audit events (containing logging audit headers) into time window.  timestamp generation and setting are handled by the audit client library under the hood. There is not API change.

add timestamp field to logging audit headers

---

singer/src/main/java/com/pinterest/singer/reader/ByteOffsetInputStream.java
singer/src/main/java/com/pinterest/singer/reader/mapped/MappedFileTBinaryProtocol.java
singer/src/main/java/com/pinterest/singer/reader/mapped/MappedThriftLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/mapped/MappedThriftReader.java
singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java
singer/src/test/java/com/pinterest/singer/reader/ThriftLogFileReaderTest.java
singer/src/test/java/com/pinterest/singer/reader/mapped/TestMappedTBinaryProtocol.java

Simple Mapped Thrift Reader implementation, this enables efficient batch loading of log data. Note that this PR only contributes the implementation without changing any critical wiring of Singer writer code making it safer to commit.

Simple Mapped Thrift Reader implementation, this enables efficient batch loading

---

singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java

Cache hostname instead of performing dynamic lookups to fix issue raise:
https://github.com/pinterest/singer/issues/44

Cache hostname instead of performing dynamic lookups

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/SingerMain.java
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
singer/src/main/java/com/pinterest/singer/environment/Environment.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/config/DirectorySingerConfiguratorTest.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

Shadow Singer to allow validation / testing of Singer allows us to perform apples to apples comparison of two singer releases in real environment without impacting existing data flows.

Shadow Singer to allow validation / testing of Singer

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/AuditEventKafkaSender.java
singer/pom.xml
thrift-logger/pom.xml

The issue: when send fails, the RecordMetadata is None and calling partition() method from it will cause NPE.
The fix: when sending a ProducerRecord, the chosen partition should be used to create a KafkaProducerCallBack instance for later reference.

Fix KafkaProducerCallback implemention in AuditEventKafkaSender.java

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/LogStreamWriter.java
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/kafka/KafkaWritingTaskFuture.java
singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java
singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java

New MemoryEfficientLogStreamProcessor to reduce memory utilization. 
**Description:**
Singer currently uses a micro-batch processing architecture which relies on in-memory buffering of data using List. This design requires substantial memory usage as all data need to be first loaded in memory instead of being directly available for streaming.
This change creates an iterator like design pattern that can be leveraged to stream data directly to the writer and let the writer create and ship micro-batches as needed. This allows only 1 LogMessage object to be buffered in memory instead of 10s or 100s (depending on configured logstream batch sizes) making Singer substantially more scalable and allowing it to ship more data without consuming more resources.
**Configurations:**
The new processor …

Add new MemoryEfficientLogStreamProcessor to reduce memory utilization

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java
thrift-logger/pom.xml

Trim last newline character for text log reader in Singer.
This configuration is activated using 
```
reader.text.trimTailingNewlineCharacter=true
```
Default is false.
Singer version 0.8.0.16

Trim last newline character for text log reader in Singer

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer-commons/src/main/thrift/text_message.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java
thrift-logger/pom.xml

Allow custom environment variables to be injected in text logs based on config.
This can be provided via config of comma separated list:
```
reader.text.prependEnvironmentVariables=USER,HOST
```
Output will contain materialized values of these environment variables; if the variable is null `-` will be added.
Output
`|USER=xyz HOST=abc|`

Allow custom environment variables to be injected in text logs based on config

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/common/LoggingAuditClientConfigDef.java
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/utils/ConfigUtils.java
singer-commons/src/main/thrift/loggingaudit_config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/writer/HeadersInjector.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/headersinjectors/LoggingAuditHeadersInjector.java
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
singer/src/test/java/com/pinterest/singer/writer/TestKafkaWriter.java
singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java
thrift-logger/pom.xml
thrift-logger/src/main/java/com/pinterest/singer/client/AuditableLogbackThriftLogger.java
thrift-logger/src/main/java/com/pinterest/singer/client/LogbackThriftLogger.java
thrift-logger/src/test/java/com/pinterest/singer/client/AuditableLogbackThriftLoggerTest.java

1. For thrift-logger, add crc feature by computing and setting the checksum field of the LogMessage
2. For singer, add crc feature in KafkaWriter.java and CommittableKafkaWriter.java, and inject the crc checksum as a header of the ProducerRecord

Add crc features for thrift-logger and singer

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
thrift-logger/pom.xml

inject ProducerRecord's Headers only when LogMessage's LoggingAuditHeaders field or checkSum field is set.

add condition check before injecting ProducerRecord's Headers

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/java/com/pinterest/singer/utils/KafkaUtils.java
singer/pom.xml
thrift-logger/pom.xml

Add linger ms to Singer

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java
thrift-logger/pom.xml

This PR commented out the size metrics added for LogMessage in https://github.com/pinterest/singer/pull/81. 
The host tag is set by calling getHostName() in SingerUtils.java and this can be optimized to reduce CPU cycles.

comment out the size metrics

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/LogStreamWriter.java
singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java
singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java
thrift-logger/pom.xml

Refactor Singer to enable writers to access LogMessageAndPosition to allow logmessages to be tracked.
This enables Singer writers to have unique id for every logmessage which can be used for sequencing / auditing etc.
Singer 0.8.0.32
Message sequencing could be critical to a Logging infrastructure, for example its one of the reasons customers in Kafka opt to use key partitioning. Singer has the assets to make sequencing a first class citizen but doesn’t do that today.
Sequencing & Iding:
Sequencing and Identification of a unique message is critical to allow the ability to be able to track / audit it through the pipeline. Luckily because we use thrift logger we can create a unique sequence by using the following tuple:
```<generating host ip><inode><offset>```
This tuple allows us to …

Refactor Singer to enable writers to access LogMessageAndPosition to

---

singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

Add MemQ serverset based restart.
The reason for not adding unit test is because the poll based watches seem to be flaky so unit test is not stable.

Add MemQ serverset based restart

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/LoggingAuditClient.java
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/LoggingAuditEventGenerator.java
singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/common/LoggingAuditClientConfigDef.java
singer-commons/src/main/thrift/loggingaudit.thrift
singer-commons/src/main/thrift/loggingaudit_config.thrift
singer/pom.xml
thrift-logger/pom.xml
thrift-logger/src/main/java/com/pinterest/singer/client/AuditableLogbackThriftLogger.java
thrift-logger/src/test/java/com/pinterest/singer/client/AuditableLogbackThriftLoggerTest.java

1. separate injecting LoggingAuditHeaders / checksum from sending out audit events:
(1) inject LoggingAuditHeaders / checksum for every message
(2) if tracked field of LoggingAuditHeaders is set true, audit event will be sent out
2. add tracked field and skipped field to loggingaudit.thrift and support passing skipped field
when calling audit method of LoggingAuditClient
3. add enableDeserialization field and messageClass field to AuditConfig struct. it will be used later
to perform thrift deserialization if configured in order to check if a message is valid or not.

Multiple improvements to thrift-logger module and singer-commons module

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/loggingaudit.thrift
singer-commons/src/main/thrift/loggingaudit_test.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
singer/src/test/java/com/pinterest/singer/writer/TestKafkaWriter.java
singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java
thrift-logger/pom.xml

Earlier, in https://github.com/pinterest/singer/pull/100, LoggingAuditHeaders and
checksum fields are set for every message. Those being audited based on some
audit rate will have messageTracked field set to true in LoggingAuditHeaders,
correspondingly audit events will be sent to Kafka for audited messages.
In this PR, refactor Singer accordingly:
(1) every message now has LoggingAuditHeaders field and checksum field, in KafkaWriter.java,
use mapOfTrackedMessageMaps to record messages being tracked (messageTracked field is true in
LoggingAuditHeaders), use mapOfInvalidMessageMaps to record invalid messages due to checksum
mismatch, use mapOfOriginalIndexWithinBucket to record the original position of invalid messages
in each partition (aka bucket).
(2) message is determined as invalid if …

separate LoggingAuditHeaders / checksum from audit events

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java

Add sampling support to Singer Memory Efficient Processor. This feature will only activate if an additional configuration is set to true, else default behavior will be preserved.
to enable this feature:
```
processor.enableDeciderBasedSampling=true
```

Add sampling support to Singer Memory Efficient Processor

---

singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java

Add defaults for buffer size and max message size to avoid requiring these values to be specified for every config

Add defaults for buffer size and max message size

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/java/com/pinterest/singer/config/Address.java
singer-commons/src/main/java/com/pinterest/singer/config/ConfigFileServerSet.java
singer-commons/src/main/java/com/pinterest/singer/config/ServersetMonitor.java
singer-commons/src/main/java/com/pinterest/singer/utils/BrokerSetChangeListener.java
singer-commons/src/main/java/com/pinterest/singer/utils/KafkaUtils.java
singer/pom.xml
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigs.java
thrift-logger/pom.xml

Remove DNS queries from Singer that may lead to slow startup

Remove DNS queries from Singer that may lead to slow startup

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/config/DirectorySingerConfigurator.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/config/DirectorySingerConfiguratorTest.java

Add capability of doing rule-based (currently only exact match) override of log configs
Can be done by setting `configOverrideDir` in `singer.properties` and have property files in that directory with `match.config.name` set to the config name to be matched, and `match.config.value` to the config value; add `override.` prefix to the configs that need to be overriden. Files will be sorted in alphabetical order and later overrides will have higher precedence over earlier ones.
Example:
In the `singer.properties` file:
```
...
singer.configOverrideDir=/path/to/override/dir
...
```
In `path/to/override/dir/100-override-kafka-buffer-memory.properties`
```
match.config.name=writer.type
match.config.value=kafka
override.writer.kafka.producerConfig.buffer.memory=100000
```
in …

Rule-based overrides for log configs

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
thrift-logger/pom.xml

Previously, a KafkaProducerMetricsMonitor thread was created for each log config, which causes a lot of threads to be created and wasting stack memory.

Fix excessive creation of KafkaProducerMetricsMonitor threads

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/kafka/KafkaWritingTaskFuture.java
singer/src/test/java/com/pinterest/singer/writer/kafka/TestCommittableKafkaWriter.java
thrift-logger/pom.xml

tl; dr: Replaced `clusterThreadPool` usage by using CompletableFutures to implement non-blocking kafka request handling
In this diff, we remove the usage of clusterThreadPool in `CommitableKafkaWriter`. Previously, the `clusterThreadPool` was allocated per cluster and used for tracking metrics of the `Future<RecordMetadata>`. This caused a lot of threads to be used if Singer is publishing to a lot of clusters. Since these threads are used only for tracking, we found out that they could be eliminated and instead refactored into `CompletableFuture`s that can be executed asynchronously with the shared common `ForkJoinPool` as long as they remain non-blocking. 
We also leverage the callback in `send` to achieve this:
```
CompletableFuture<RecordMetadata> future = new CompletableFuture<>(); …
```

Refactor CommittableKafkaWriter to use non-blocking request handling

---

thrift-logger-python/requirements.txt
thrift-logger-python/setup.py

This library is not available in pypi so should not be treated as a requirement for the open source project.

Remove internal package from open source project

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/reader/ThriftLogFileReaderTest.java

Porting same feature inTextLogFileReader which allows Singer to inject headers to the messages based on config-specified environment variables.

Header injection from environment variables for ThriftLogFileReader

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/monitor/DefaultLogMonitorTest.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

This is to add another type of sampling besides the existing message-level sampling. Instance level sampling allows a logstream to be enabled/disabled by a percentage of the fleet, rather than a percentage of the messages per host. This allows canary-style rollouts of logs. Another minor improvement is logstreams that have a zero-value decider will be removed from the actively monitored logstreams, thus stop getting tracked in the stuck logstream monitor.

Add instance level sampling

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
thrift-logger/pom.xml

Singer text reader is using the wrong config for max message size. Bump version to 0.8.0.59 as well.

Fix Singer textReader bug using wrong config for max message size

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java
thrift-logger/pom.xml

On some rare occasions when the volume is extremely low, the `partitionsFor` method of the kafka producer will fail due to SSL issues. Since the producer isn't reset during startCommit failures, the producer will get stuck when writes are happening. This fixes the issue by resetting the producer when a failure occurs.

Fix startCommit partitionsFor exception handling, bump version to 0.8.0.63

---

singer/src/main/java/com/pinterest/singer/writer/kafka/CommittableKafkaWriter.java

Hi,
This PR fixes 1 violations of [Sonar Rule 2142: '"InterruptedException" should not be ignored'](https://rules.sonarsource.com/java/RSPEC-2142). This is done without introducing any new violations of Sonar rules.
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2142](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#interruptedexception-should-not-be-ignored-sonar-rule-2142).
P.S.: Note that this PR is not created/submitted by a bot. If you have any feedback, please leave them as comments.

Fix violations of Sonar rule 2142

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/admin/AdminServer.java
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
thrift-logger/pom.xml

This commit adds an AdminServer module that will allow admin operations to be performed via a Unix domain socket (UDS). UDS server implementation is backed by the junixsocket dependency. Besides file permissions, there is also a simple pid based allowlist for commands. 
The only command provided now is the `stop` command, which is will allow Singer to drain logs before getting ready to be terminated.
A simple way to perform this operation from shell would be to use `nc` (nc-freebsd) with the following command:
`echo "stop" | nc -U /tmp/singer/admin.sock`
The command will block until all logstreams are drained, or Singer is terminated. The command will send back the message `done` to the connection when the draining is complete, signaling the script that Singer is ready to be terminated. …

Initial implementation of AdminServer with draining command

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/common.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/KafkaMessagePartitioner.java
singer/src/main/java/com/pinterest/singer/writer/KafkaWriter.java
singer/src/main/java/com/pinterest/singer/writer/partitioners/FixedPartitionsPartitioner.java
singer/src/test/java/com/pinterest/singer/writer/partitioners/TestFixedNumberPartitionPartitioner.java
thrift-logger/pom.xml

Allow configs to be passed to the partitioner via `writer.kafka.producerConfig.partitioner.<config>` keys, and add a partitioner that allows fixed number of partitions to be written to (extension of `SinglePartitionPartitioner`)

Make partitioner configurable and add FixedPartitionsPartitioner

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/partitioners/FixedPartitionsPartitioner.java
thrift-logger/pom.xml

Previously the ThreadLocalRandom instance was kept as a member of the partitioner and populated during configure phase, causing the random seeds to be the same each time.

Fix incorrect usage of ThreadLocalRandom

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
thrift-logger/pom.xml

This allows log configs to specify `skipDraining` and skip the draining. This is useful for application logs that cannot be stopped but not critical.

Allow logstreams to be skipped during draining

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/LogStream.java
thrift-logger/pom.xml

Previously if a log file is deleted during logstream initialization phase, an NPE will cause the logstream to be empty.

Add try-catch during initialize phase to deal with log rotation

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
thrift-logger/pom.xml

`singer.processor.committed_position_reset` metric was using the wrong log tag, causing high cardinality for some use cases

Fix metrics tagging

---

singer-commons/src/main/thrift/config.thrift

Add default retention of 2hrs for Singer, currently there is no default retention for Singer. 2hrs is a low enough value for data to be saved for local investigation without leaving large amount of unused data.

Add default retention of 2hrs for Singer

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/kubernetes/KubeService.java
singer/src/test/java/com/pinterest/singer/kubernetes/TestKubeService.java
thrift-logger/pom.xml

Adding support for pod log directories with pod uid in their names: `namespace_name_uid` as well as the original format `namespace_name`. Note that for 1 unique `namespace` + `name` + `uid` combination, there can't be two directories, e.g: `somenamespace_xyz` and `somenamespace_xyz_123` won't be present at the same time.
Testing: Replace Singer jar with code changes in an EC2 host running singer in kubernetes mode. After enabling the `_uid` directories, it was verified that singer was able to pick up the logs inside every pod directory and properly generate the `.` file for CMP process to do cleanup.

Add K8s uid support for pod log directories

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/text_message.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReaderFactory.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java
singer/src/test/java/com/pinterest/singer/reader/ThriftLogFileReaderTest.java
thrift-logger/pom.xml

- Tested with unit tests to ensure "availabilityZone: "us-east-1a" shows up in log msgs to kafka.
mvn test -pl singer -am passes
- Tested in devapp w/ thrift logs and text logs, and each of those with and without EC2 env set. 
If EC2 env is set, "availabilityZone: "us-east-1a". 
Else env is not set, "availabilityZone: "n/a".

Add AZ Header to Kafka Logs

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/kubernetes/KubeService.java
singer/src/main/java/com/pinterest/singer/tools/KubeServiceChecker.java
singer/src/test/java/com/pinterest/singer/kubernetes/TestPodLogCycle.java
singer/teletraan/conf/singer.kubernetes.properties
thrift-logger/pom.xml

To exclude pod log directories that have their dedicated logging agent, a flag named "ignorePodDirectory" is introduced. Singer will ignore the processing and monitoring of directories marked with this flag. For instance, if the pod log directory is `/var/log/podlogs/my_pod/` and the flag directory `ignorePodDirectory=Ignore`, singer will refrain from processing any data related to this specific pod if `/var/log/podlogs/my_pod/Ignore` exists

Ignore pods running singer in dual mode

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/kubernetes/KubeService.java
thrift-logger/pom.xml

Return false from `checkIgnoreDirectory(String podName)` when ignorePodDirectory is empty or null

Fix ignore pod logic when flag is set to null or empty

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/config/Decider.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java
singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java
singer/src/test/java/com/pinterest/singer/utils/TestSingerUtils.java

Disable a logstream if fleet level disable decider is set to 100, otherwise continue with regular execution. This decider needs to be in the format: `singer_disable_<logstream_name>___<hostname_prefix>___decider` where all non non-alphanumeric charcters in `logstream_name` are replaced by underscores. Also introduce a utility function to retrieve hostname prefix list.

Add fleet level disable decider logic

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/SingerMain.java
thrift-logger/pom.xml

When a log directory contains a large number of files, the initialization of all log streams in the directory can take some time for Singer after a restart. However, by initiating the metrics service prior to `SingerSettings.initialize()`, we can continue to publish metrics while Singer finalizes the log stream initialization process.

Initialize ostrich metrics service before main initialize

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/config/DirectorySingerConfigurator.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/config/DirectorySingerConfiguratorTest.java
thrift-logger/pom.xml

Check if the regex provided in `logStreamRegex` is valid when parsing log configurations. This prevents an issue where an incorrect regex could silently fail the FileSystemMonitor in Kubernetes mode

Validate logStreamRegex

---

singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java

When Singer is processing files that are symlinks in different directories, the processor goes into a failure loop when the target file of the symlink is removed. This happens because the LogStream tracks the symlink and not the target file, thus the monitor does not update the LogStram when deletion event comes in.

Fix FNF exception with dangling symlinks

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java
thrift-logger/pom.xml

Make sure hostnames without a delimiter can still function correctly when naming AWS file format. Injecting the hostname for S3WriterTest for consistency.

S3 Writer Test Fix

---

pom.xml
singer-commons/pom.xml
singer-commons/src/main/thrift/config.thrift
singer/pom.xml
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/reader/ByteOffsetInputStream.java
singer/src/main/java/com/pinterest/singer/reader/OffsetInputStream.java
singer/src/main/java/com/pinterest/singer/reader/RandomAccessFileInputStream.java
singer/src/main/java/com/pinterest/singer/reader/ThriftReader.java
singer/src/main/java/com/pinterest/singer/reader/pooled/PooledByteBufInputStream.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/reader/ThriftLogFileReaderTest.java
singer/src/test/java/com/pinterest/singer/reader/pooled/PooledByteBufInputStreamTest.java
thrift-logger/pom.xml

This PR introduces a buffered input stream implementation that leverages Netty's pooled direct `ByteBuf` for buffering, instead of traditional nio ByteBuffers or byte arrays. This approach aims to minimize garbage collection overhead by reusing pooled buffers rather than repeatedly creating new ones for each stream. This optimization is particularly useful for scenarios where a single Singer instance handles thousands of log streams.

Pool reader buffers

---

singer/src/main/java/com/pinterest/singer/writer/s3/ObjectUploaderTask.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java

S3Writer refactor changes included:
- Delete unused and redundant helper methods and class fields
- Introduce helper functions to reduce code duplicates
- Change `File.renameTo()` to `Files.move()` for buffer file renaming. The latter is much more reliable and offers better error handling
- Consolidate upload logic to one single method
- Add more comments and javadoc
- Add metric for number of messages written to buffer (so it can be compared with upstream logger metric)
- Introduce "logName" derived from singer log config name to use instead of `logStream.getLogStreamName()`

Refactor S3Writer class to improve code structure

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/s3/ObjectUploaderTask.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java

This PR introduces 2 new configs to S3Writer to allow for more customizable format for object uploads: 
- `filenamePattern` : A regex to extract fields/tokens out of the filename
- `filenameTokens` : A list of tokens extracted from filenamePattern, these are extracted automatically but can also be set for testing
`keyPrefix` and `filenameFormat` are also replaced with `keyFormat` so that tokens extracted from the flename can be used in `keyFormat` by following the syntax: `%{TOKEN}`, e.g: 
```
writer.type=s3
writer.s3.maxFileSizeMB=5
writer.s3.minUploadTimeInSeconds=30
writer.s3.bucket=my-bucket
writer.s3.keyFormat=%{service}/%{index}/my_log.%TIMESTAMP
writer.s3.maxRetries=3
writer.s3.filenamePattern=^(?<service>[a-zA-Z0-9]+)_.*_(?<index>\\d+)\\.log$
```
Additionally, we add some default …

Implement custom format for object keys uploaded by S3Writer

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/s3/ObjectUploaderTask.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

Add configuration to add canned acl to objects uploaded by S3Writer, more info on canned ACLs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

S3Writer: Add canned acl support

---

singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java

1. Append UUID at the end of buffer file to avoid collisions when multiple log streams process the same file
2. Remove high cardinality tags from metrics

S3Writer improvements

---

singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/test/java/com/pinterest/singer/monitor/FileSystemMonitorTest.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java

This resolves a problem where Singer attempts to initialize logstreams for watermark files when the regex in the logstream configuration isn't left-bounded. For example if we have a regex: `.*test.*` and in the directory we have the following files: 
```
.singer.my_logstream.test_001  <---- the watermark file
test_001 <---- the logfile
```
Singer will try to initialize logstreams for both files, resulting in a third watermark that tracks the watermark file:
```
.singer.my_logstream..singer.my_logstream.test_001 <---- unwanted watermark file
.singer.my_logstream.test_001  <---- watermark file
test_001 <---- logfile
```
In some cases when filenames are long, the processor won't be able to persist progress onto the unwanted watermark files due to filename too long exceptions.
Test Plan: …

Exclude hidden files from logstream regex discovery

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/processor/MemoryEfficientLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/reader/LogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java

Introducing the config `filterMessageRegex` so that only messages that match the pattern provided will be returned to the processor. This does not modify the existing TextMessageReader logic, instead we leverage the headers as a DOT so that the processor knows that message should be skipped if it contains the special header `skipMessage`. The skipping logic is the same as the decider based sampling logic.

Add simple regex-based message filtering to text reader

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/main/java/com/pinterest/singer/transforms/MessageTransformer.java
singer/src/main/java/com/pinterest/singer/transforms/MessageTransformerFactory.java
singer/src/main/java/com/pinterest/singer/transforms/RegexBasedModifier.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/processor/TestMemoryEfficientLogStreamProcessor.java
singer/src/test/java/com/pinterest/singer/reader/TestTextLogFileReader.java
singer/src/test/java/com/pinterest/singer/transforms/RegexBasedModifierTest.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

Introducing a message transformer interface for `LogFileReaders`, enabling the transformation of messages before they are forwarded to `LogStreamProcessors`. The desired transformer along its configuration can be defined within a LogStream configuration file as follows:
```
transformer.type=regex_based_modifier
transformer.regex_based_modifier.regex=(?s)^(.+?) (INFO|ERROR|OFF|DEBUG|SEVERE|WARN) (null) (.*)$
transformer.regex_based_modifier.modifiedMessageFormat={log_level: $2, message: $4, timestamp: $1}
transformer.regex_based_modifier.appendNewLine=true
```
Please note that configuring message transformers is optional, and only one transformer can be applied per log stream. Currently, we are introducing a single transformer: `RegexBasedModifier`. This transformer uses a regular …

Add message transformer interface

---

singer/src/main/java/com/pinterest/singer/transforms/RegexBasedModifier.java
singer/src/test/java/com/pinterest/singer/transforms/RegexBasedModifierTest.java

Fix the case where messages containing special tokens `$n` would get the processor stuck in the transform function if the token existed in the regex group map. New implementation traverses through `messageFormat` string and builds the result by replacing the indexes with the group values, instead of using multiple `String.replace()` calls.

Fix RegexBasedModifier transform 

---

singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/S3WriterTest.java

Enhance the s3Key building function:
1. Utilize `StringSubstitutor` from apache-commons library for token replacement
2. Add Year, Month, Day, Hour, Minute, Seconds to default tokens for more granular date/time prefixing
3. Allow environment variables to be replaced into s3Key
4. Change formatting for tokens:
- `%{}` will continue to be used for regex tokens
- `{{}}` will now be used for default tokens
- `${}` will be used for environment variables

Enhance s3 object key formatting

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/s3/PutObjectUploader.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3ClientManager.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3ObjectUpload.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Uploader.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/s3/S3ClientManagerTest.java
singer/src/test/java/com/pinterest/singer/writer/s3/S3WriterTest.java

This PR enhances the S3writer in a few ways:
1. The uploading mechanism is now pluggable,  now uploaders have to extend `S3Uploader` class. This change simplifies the implementation of uploads to S3 using alternative APIs, such as `MultiPartUpload` or `TransferManager`. This ensures backwards compatibility so newer implementations are easier to roll out. New config is added to reference the uploader class: `optional string uploaderClass = "com.pinterest.singer.writer.s3.PutObjectUploader"`
2. Add support for uploading to buckets in different regions. The region needs to be specified when creating a new S3Client, this means one Singer instance can't upload to multiple buckets in different regions. To enable this, we introduce a new `S3ClientManager` which will create a new client per …

Introduce s3 client manager and s3 uploaders

---

singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/s3/S3WriterTest.java

Changing the buffer file naming to `logName.dirName.fileName.buffer`, which follows the watermark file naming model. This helps by:
1. Reduce the amount of buffer files generated: the previous naming model created too many buffer files because of the uuid appended at the end. 
2. Allow S3Writers to continue from buffer file after restart in case upload fails when closing the writer
3. Avoid multi-directory conflicts
4. Avoid conflicts between two or more different log streams processing the same file
Other conflicts can be handled by specifying a different s3 buffer directory per log stream
Also cleaning the classes by removing unused code and tests

Change buffer file naming

---

singer/pom.xml
singer/src/main/java/com/pinterest/singer/writer/s3/S3Writer.java
singer/src/test/java/com/pinterest/singer/writer/s3/S3WriterTest.java

- Add STS dependency to allow S3Client to use Web Identity Tokens
- Remove default UUID append at the end of object key, users can add it if needed.

S3Writer  updates

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/common/SingerLog.java
singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/kubernetes/KubeService.java
singer/src/main/java/com/pinterest/singer/kubernetes/PodMetadataTracker.java
singer/src/main/java/com/pinterest/singer/kubernetes/PodMetadataWatcher.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/kubernetes/TestKubeService.java
singer/src/test/resources/pods-badresponse.json
singer/src/test/resources/pods-goodresponse.json

Introducing a new singleton class `PodMetadataWatcher` that implements the `PodWatcher` interface. Whenever a pod is created or deleted, this class will query Kubelet to parse the pod's metadata and store it in a map. Since this watcher is registered before LogStreamManager, the metadata for each pod should be fresh whenever each log stream is created. 
We also add a new `podMetadata` field to `SingerLog` to attach pod metadata per log in k8s mode.
The pod metadata to track is defined by:
```
7: optional list<string> podMetadataFields;
```

Add support for pod metadata header injection

---

singer/src/main/java/com/pinterest/singer/environment/EnvVariableBasedEnvironmentProvider.java
singer/src/main/java/com/pinterest/singer/environment/Environment.java
singer/src/main/java/com/pinterest/singer/environment/EnvironmentProvider.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReader.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java

Integrate an "accountId" field into the Environment class to allow cloud-based environment providers to track it.

Add support for environment account id

---

pom.xml
singer-commons/pom.xml
singer/pom.xml
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java
thrift-logger/pom.xml

`pod_metadata_enabled`  is not correctly formatted with singer namespace prefix and can get have high cardinality when running in k8s.
path tag in `singer.thrift_reader.skip_message` can also lead to high tag cardinality.
Bumping version to `0.8.0.95`

High tag cardinality metrics changes

---

singer/pom.xml
singer/src/main/java/com/pinterest/singer/common/LogStream.java
singer/src/main/java/com/pinterest/singer/common/SingerSettings.java
singer/src/main/java/com/pinterest/singer/monitor/LogStreamManager.java
singer/src/main/java/com/pinterest/singer/monitor/MissingDirChecker.java
singer/src/main/java/com/pinterest/singer/monitor/RecursiveFSEventProcessor.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/utils/SingerUtils.java
singer/src/test/java/com/pinterest/singer/kubernetes/TestPodLogCycle.java
singer/src/test/java/com/pinterest/singer/monitor/FileSystemMonitorTest.java
singer/src/test/java/com/pinterest/singer/monitor/LogDirectoryScannerTest.java
singer/src/test/java/com/pinterest/singer/monitor/MissingDirCheckerTest.java
singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java

Adding support for wildcard use in all parts of directory configs, it currently is limited to only last part of directory string. In addition, refactoring certain part of the code structure to improve readability. List of main changes:
- Change `logConfigMap` to use `Pair<>` for keys: This map is essentially only used in Kubernetes mode by `RecursiveFSEventProcessor`. During the pod directory traversal, we use this map to determine if there are any configs left for directories in a sublevel. Now that we have wildcards in the directory names, we can no longer use `subMap()` function reliably. Thus, we change the approach to directly use directory depth for this purpose. The Pair consists of directory depth (for ordering) and directory (for tracking, can contain wildcard).
- Change approach …

Allow multiple directories per log config

---

singer/src/main/java/com/pinterest/singer/reader/ThriftLogFileReader.java

Adding log file name to message exceeds size warn in thrift reader. Tested in dev environment:
```
2025-03-28 20:39:48,473 [Processor: 2] (com.pinterest.singer.reader.ThriftLogFileReader:147) WARN  Found a message at offset 954316 that exceeds the size limit in log file: /mnt/thrift_logger/log-benchmark_singer-benchmarking_0.log with messageSize =  141
```

Improve message size warn message

---

singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java
singer/src/test/java/com/pinterest/singer/processor/DefaultLogStreamProcessorTest.java

- Avoid removing log stream from logFilePaths when file does not exist and add a metric for visibility.
- Improve error handling when inode and base file don't match after rotation during new reader initialization

Fix broken symlink handling logic

---

singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/test/java/com/pinterest/singer/monitor/MissingDirCheckerTest.java

`FilenameUtils.wildcardMatch()` does not work as expected and can lead to initialization of unwanted directories. Switching to `FileSystems.getDefault().getPathMatcher(...)` with glob pattern yields expected results, see: https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-

Improve wildcard directory discovery

---

singer/src/main/java/com/pinterest/singer/common/SingerMetrics.java
singer/src/main/java/com/pinterest/singer/config/Decider.java

This metric will help determine what deciders each host is accessing.

Add metrics for decider access in singer

---

singer-commons/src/main/thrift/config.thrift
singer/src/main/java/com/pinterest/singer/common/SingerConfigDef.java
singer/src/main/java/com/pinterest/singer/utils/LogConfigUtils.java
singer/src/main/java/com/pinterest/singer/writer/s3/PutObjectUploader.java
singer/src/main/java/com/pinterest/singer/writer/s3/S3Uploader.java
singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java

This PR adds a contentType property to the S3Writer to allow specifying the content type for files uploaded to S3. This is to enable setting the correct Content-Type metadata for S3 objects, improving compatibility and browser handling.

Add content type property to S3Writer
